name: CI for Python Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Bước 2: Cài đặt Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    # Bước 3: Cài đặt các thư viện từ requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Bước 4: Chạy test với pytest và sinh báo cáo HTML
    - name: Run Pytest
      run: |
        pytest --maxfail=1 --disable-warnings -q --html=report.html --self-contained-html

    # Bước 5: Lưu file report làm artifact
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html
