name: Python Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Cài dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Chạy pytest chỉ trong thư mục unit
      - name: Run Unit Tests
        run: |
          pytest tests/unit --maxfail=1 --disable-warnings -q --html=reports/report.html
      # 5. Upload artifactt
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: github-test-report
          path: reports/report.html

